### PR TITLE
Add wifi ISM43362 driver to Easy connect

### PR DESCRIPTION
**Pull request by adustm**
Hello,
The wifi ism43362 is the wifi module of DISCO_L475VG_IOT01A and DISCO_F413ZH  platforms.

Could you add this feature to the easy connect repository ?
Kind regards
Armelle

### CODE REVIEW

**Comment by teetak01** [comment]
@adustm could you add read-access to the repository?

**Comment by adustm** [comment]
>  could you add read-access to the repository?


@teetak01 Done, let me know if it works for you.
Kind regards

**Comment by teetak01** [comment]
Thanks @adustm now the PR checks pass. Could you still rebase this locally and push the updated version? I can then take it in.

**Review by teetak01 — APPROVED** [review]

**Comment by adustm** [comment]
Hello @teetak01 
Rebase done.

Kind regards

**Comment by teetak01** [comment]
Thanks!

**Pull request merged**
