### PR TITLE
Update wnc14a2a-driver.lib

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Please let me know what the two failing checks are as the results files are inaccessible to me.

**Comment by teetak01** [comment]
Hi @jflynn129 its failing with all compilers (using Mbed OS 5.8.1)

```
[Error] WNC14A2AInterface.h@171,1: expected class-name before '{' token
[ERROR] In file included from ./easy-connect/wnc14a2a-driver/WNC14A2AInterface/WNC14A2AInterface.cpp:31:0:
./easy-connect/wnc14a2a-driver/WNC14A2AInterface/WNC14A2AInterface.h:171:1: error: expected class-name before '{' token
 
```{

**Comment by teetak01** [comment]
I think that build-fail is actually pre-existing issue in this driver which broke when Mbed OS 5.8.1 was merged in to mbed-os-example-client.

**Comment by teetak01** [comment]
Also earlier also this failed in different error:  DISCO_L475VG_IOT01A_ISM43362 with ARMC6

```
Error: L6218E: Undefined symbol __HeapLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackTop (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __end__ (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __mbed_krbs_start (referred from l4_retarget.o).
Error: L6218E: Undefined symbol __mbed_sbrk_start (referred from l4_retarget.o).
```

**Comment by ghost** [comment]
Thank you, I'll look into it.

**Comment by ghost** [comment]
Updated library to d74533bf40c6907575677bcea37812fb8fded5a4 which has fixes.

**Comment by ghost** [comment]
I am unable to see the details on the two failures, can you send the info to me.  Is there some way that failure text can be auto-posted to the pull request so submitters can see the details of failures?

BTW, @teetak01 how are the errors you listed above generated by the library, I am not touching mbed_boot or l4_retarget files at all.

**Comment by ghost** [comment]
@dlfryar can you forward me the failures listed above?

**Comment by teetak01** [comment]
Hi @jflynn129 
 `mbed compile -m NUCLEO_L476RG -t ARMC6
`

```
Link: mbed-os-example-client
Warning: L3912W: Option 'legacyalign' is deprecated.
Warning: L3912W: Option 'no_strict_wchar_size' is deprecated.
Warning: L3912W: Option 'no_strict_enum_size' is deprecated.
Warning: L6433W: Ignoring incompatible enum size attribute on object iostream.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_virtual.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object memory.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object locale.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object ios.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object abort_message.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object private_typeinfo.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object exception.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object new.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object string.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object system_error.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object mutex.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object exception.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object stdexcept.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object typeinfo.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object stdexcept.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_handlers.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_noexception.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_default_handlers.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_exception_storage.cpp.o.
Warning: L6439W: Multiply defined Global Symbol SimpleSpirit1::enable_spirit_irq() defined in invalid_group(SimpleSpirit1.o) rejected in favor of Symbol defined in .text._ZN13SimpleSpirit117enable_spirit_irqEv(radio_spi.o).
Warning: L6439W: Multiply defined Global Symbol mbed::Callback<void(int)>::call(int) const defined in invalid_group(SimpleSpirit1.o) rejected in favor of Symbol defined in .text._ZNK4mbed8CallbackIFviEE4callEi(SerialBase.o).
Warning: L6439W: Multiply defined Global Symbol mbed::Callback<void()>::call() const defined in invalid_group(ATParser.o) rejected in favor of Symbol defined in .text._ZNK4mbed8CallbackIFvvEE4callEv(SerialBase.o).
Warning: L6439W: Multiply defined Global Symbol void SPWFSAxx::attach<SpwfSAInterface, void(SpwfSAInterface::*)()>(T1*, T2) defined in invalid_group(SPWFSAxx.o) rejected in favor of Symbol defined in .text._ZN8SPWFSAxx6attachI15SpwfSAInterfaceMS1_FvvEEEvPT_T0_(SpwfSAInterface.o).
Warning: L6439W: Multiply defined Global Symbol std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string__sub_object(const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, unsigned, unsigned, const std::__1::allocator<char>&) defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2ERKS5_jjRKS4_(string.cpp.o) rejected in favor of Symbol defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2ERKS5_jjRKS4_(WNC14A2AInterface.o).
Warning: L6439W: Multiply defined Global Symbol std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::~basic_string__sub_object() defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev(string.cpp.o) rejected in favor of Symbol defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev(WNC14A2AInterface.o).
Warning: L6439W: Multiply defined Global Symbol mbed::DirHandle::readdir()::ent defined in invalid_group(Dir.o) rejected in favor of Symbol defined in .bss._ZZN4mbed9DirHandle7readdirEvE3ent(FileSystem.o).
Error: L6218E: Undefined symbol __HeapLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackTop (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __end__ (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __mbed_krbs_start (referred from l4_retarget.o).
Error: L6218E: Undefined symbol __mbed_sbrk_start (referred from l4_retarget.o).
Finished: 0 information, 30 warning and 6 error messages.
[ERROR] Warning: L3912W: Option 'legacyalign' is deprecated.
Warning: L3912W: Option 'no_strict_wchar_size' is deprecated.
Warning: L3912W: Option 'no_strict_enum_size' is deprecated.
Warning: L6433W: Ignoring incompatible enum size attribute on object iostream.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_virtual.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object memory.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object locale.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object ios.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object abort_message.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object private_typeinfo.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object exception.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object new.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object string.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object system_error.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object mutex.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object exception.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object stdexcept.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object typeinfo.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object stdexcept.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_handlers.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_noexception.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_default_handlers.cpp.o.
Warning: L6433W: Ignoring incompatible enum size attribute on object cxa_exception_storage.cpp.o.
Warning: L6439W: Multiply defined Global Symbol SimpleSpirit1::enable_spirit_irq() defined in invalid_group(SimpleSpirit1.o) rejected in favor of Symbol defined in .text._ZN13SimpleSpirit117enable_spirit_irqEv(radio_spi.o).
Warning: L6439W: Multiply defined Global Symbol mbed::Callback<void(int)>::call(int) const defined in invalid_group(SimpleSpirit1.o) rejected in favor of Symbol defined in .text._ZNK4mbed8CallbackIFviEE4callEi(SerialBase.o).
Warning: L6439W: Multiply defined Global Symbol mbed::Callback<void()>::call() const defined in invalid_group(ATParser.o) rejected in favor of Symbol defined in .text._ZNK4mbed8CallbackIFvvEE4callEv(SerialBase.o).
Warning: L6439W: Multiply defined Global Symbol void SPWFSAxx::attach<SpwfSAInterface, void(SpwfSAInterface::*)()>(T1*, T2) defined in invalid_group(SPWFSAxx.o) rejected in favor of Symbol defined in .text._ZN8SPWFSAxx6attachI15SpwfSAInterfaceMS1_FvvEEEvPT_T0_(SpwfSAInterface.o).
Warning: L6439W: Multiply defined Global Symbol std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string__sub_object(const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, unsigned, unsigned, const std::__1::allocator<char>&) defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2ERKS5_jjRKS4_(string.cpp.o) rejected in favor of Symbol defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2ERKS5_jjRKS4_(WNC14A2AInterface.o).
Warning: L6439W: Multiply defined Global Symbol std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::~basic_string__sub_object() defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev(string.cpp.o) rejected in favor of Symbol defined in .text._ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev(WNC14A2AInterface.o).
Warning: L6439W: Multiply defined Global Symbol mbed::DirHandle::readdir()::ent defined in invalid_group(Dir.o) rejected in favor of Symbol defined in .bss._ZZN4mbed9DirHandle7readdirEvE3ent(FileSystem.o).
Error: L6218E: Undefined symbol __HeapLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackTop (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __end__ (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __mbed_krbs_start (referred from l4_retarget.o).
Error: L6218E: Undefined symbol __mbed_sbrk_start (referred from l4_retarget.o).
Finished: 0 information, 30 warning and 6 error messages.

[mbed] ERROR: "/usr/bin/python" returned error code 1.
[mbed] ERROR: Command "/usr/bin/python -u /builds/ws/easy-connect/1c7e0d06/mbed-os-example-client/mbed-os/tools/make.py -t ARMC6 -m NUCLEO_L476RG --source . --build ./BUILD/NUCLEO_L476RG/ARMC6" in "/builds/ws/easy-connect/1c7e0d06/mbed-os-example-client"
```

**Comment by ghost** [comment]
Thank you @teetak01 , maybe you can help me understand the failure, I do not define or set the symbols mentioned below, nor do I modify the files mbed_boot.* or l4_retarget.*

It seems  these failures are unrelated to the library itself,  Should my library be defining these symbols for some reason? 

Error: L6218E: Undefined symbol __HeapLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackLimit (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __StackTop (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __end__ (referred from mbed_boot.o).
Error: L6218E: Undefined symbol __mbed_krbs_start (referred from l4_retarget.o).
Error: L6218E: Undefined symbol __mbed_sbrk_start (referred from l4_retarget.o)

It appears that the mbed-os-example-client makefile/build-script is not including the two files (mbed_boot.* and l4_retarget.*) for some reason.

**Comment by teetak01** [comment]
I think those might actually be bugs in Mbed OS 5.8/5.8.1. ARMC6 support is a bit flaky still on the OS side.

**Comment by teetak01** [comment]
@0xc0170 can you comment on this? Is there any known issues with DISCO_L475VG_IOT01A_ISM43362 and  NUCLEO_L476RG_WIFIX when compiling for Mbed OS 5.8.1 with ARMC6?

These were still working with Mbed OS 5.7.4

**Comment by ghost** [comment]
Looks like the linker is choosing to use string operations being used in the driver over those defined in string.cpp library module; which explains why all the stack/heap defines are undefined.

**Comment by 0xc0170** [comment]
@teetak01 We do not support ARMC6 at the moment. 

However there can be a bug. Can you test with ARMC5 ? The definitions that are reported to be missing,should not be. TWO RAM REGION that was added by ST to some targets was only for IAR and GCC ARM. Not valid for ARMCC but ther emight be a condition not handled - thus you are seeing this error about missing some definitions. If you cna report this to mbed os repository with details how to reproduce.

**Comment by teetak01** [comment]
This is compiling fine with ARMC5, IAR7 and GCC_ARM. I think I need to install ARMC6 on my machine tomorrow and recheck this.

It can be that I might need to disable part of the ARMC6 builds in this repository for now. The PR itself seems to be fine.

**Comment by 0xc0170** [comment]
@teetak01 yes please,ARMC6 is not yet supported (up to mbed OS 5.8). It would be nice to fix it though (once we get more traction on ARMC6 feature branch, this bug will appear there). Feel free to report to mbed OS this and we will have a look

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
I created an issue to Mbed OS (https://github.com/ARMmbed/mbed-os/issues/6548) and disabled the ARMC6 for most of the ST-boards for now.

Cloud Client compiles fine for ARMC6, so we have been already maintaining that as part of our CI to prevent any regression.

**Review by teetak01 — APPROVED** [review]
The build-fails are unrelated to this PR.

**Comment by teetak01** [comment]
@jflynn129 would you mind adding some information to the commit-msg about what has been changed in the driver update?

**Comment by ghost** [comment]
I did as asked, the commit id changed to 9748e010ca35d30b88a106216481f59c42966f34

**Comment by teetak01** [comment]
@jflynn129 I do not see any changes? Did you push the commit yet?

**Comment by teetak01** [comment]
Thanks.

**Comment by ghost** [comment]
Thanks!

**Pull request merged**
