### PR TITLE
Support for STM WiFi Expansion Boards

### PR DESCRIPTION
**Pull request by betzw**
Removes also the need for dedicated link to `ATParser`

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
Need testing - @JammuKekkonen  - can you give a hand? Also, it does introduce an "API" change with the renaming of the WiFi-stack, but as we haven't yet "officially" released it - I'm fine with that.
If testing OK from @JammuKekkonen  - let's merge it in.

**Review by JammuKekkonen — CHANGES_REQUESTED** [review]
Does not compile for targets which define DEVICE_SERIAL_FC.

SPWFSAxx class has switched from using BufferedSerial to UARTSerial, but UARTSerial inherits SerialBase privately so SerialBase::set_flow_control is not available. Called in https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/blob/master/SPWFSAxx.cpp#L124.

**Comment by betzw** [comment]
Well, on the `master` branch of `mbed-os` this is available and as far as I know it's the only way to enable flow control using `UARTSerial`. Pls. correct me if I wrong!
In case I am right, when will the accessibility to `SerialBase::set_flow_control ()` be included in an official release of `mbed-os`?!?

**Comment by JammuKekkonen** [comment]
Seems to be planned for 5.7.0
https://github.com/ARMmbed/mbed-os/pull/5088

**Comment by betzw** [comment]
Do you know about a way to check the version of `mbed-os` e.g. via macros?

**Comment by JammuKekkonen** [comment]
https://github.com/ARMmbed/sd-driver/blob/ae7e7440054c9447f8255bdccbcc523b3f6dffe4/SDBlockDevice.cpp#L151 has an example. macros defined in mbed-os/mbed.h

**Comment by JanneKiiskila** [comment]
Master doesn't have any "versions", it's just the master. @kjbracey-arm - do you know the serial status?

**Comment by betzw** [comment]
I have updated both the `wifi-x-nucleo-idw01m1` repo and this one trying to use version macros for being able to compile also the official `mbed-os` releases.
Pls. give it a try!

**Review by teetak01 — APPROVED** [review]
Looks good to me. Passes our internal tests and builds.

@JammuKekkonen did you have any further comments?

**Comment by JammuKekkonen** [comment]
Looks good. Tested the driver with L476RG+IDW01M1, no issues.

**Review by JammuKekkonen — APPROVED** [review]

**Pull request merged**
