### PR TITLE
Add support for `X-NUCLEO-IDW01M1`

### PR DESCRIPTION
**Pull request by betzw**

### CODE REVIEW

**Review by MarceloSalazar — APPROVED** [review]

**Comment by MarceloSalazar** [comment]
LGTM.
We should get this https://github.com/ARMmbed/mbed-os-example-client/issues/303 resolved before merging.

**Comment by JanneKiiskila** [comment]
Well, actually we can merge to this one anytime - this is just an enabler and by itself does not break anything, anywhere. It's another issue if we want to merge this then to mbed-os-example-client, until we get have mbed OS 5.6.0 + required changes on top of that.

**Review by JanneKiiskila — APPROVED** [review]

**Comment by JammuKekkonen** [comment]
This will cause two different versions of ATParser to be present in the sources since esp8266 also uses that library but has been locked to earlier version.

That sometimes causes compilation error (since wifi-x-nucleo-idw01m1/SPWF01SA/SPWFSA01.cpp finds esp8266-driver/ESP8266/ATParser/ATParser.h to include but that doesn't have the needed constructor definition) and sometimes linking error.

**Comment by MarceloSalazar** [comment]
> That sometimes causes compilation error 

Maybe avoid this using the corresponding `.mbedignore` file? Although I have to say it's annoying having to use and maintain those files.

**Comment by JammuKekkonen** [comment]
The issue of multiple ATParsers could potentially be fixed by adding ATParser as library directly under easy-connect and making .mbedignore for easy-connect to ignore esp8266-driver/ESP8266/ATParser/* and wifi-x-nucleo-idw01m1/SPWF01SA/ATParser/*

It has obviously some potential drawbacks, e.g in case different drivers actually require different ATParser versions.

**Comment by betzw** [comment]
Is there any effort to enhance the build system / `mbed-cli` to not compile and link the same repo more than one time?

**Comment by janjongboom** [comment]
@betzw Well, it's a bit hard which one you pick if they use different versions. Regardless, I think the original idea was that ATParser would move to mbed-os core, but not sure what the status of that is right now @sarahmarshy @sg-.

I think @JammuKekkonen 's suggestion would be good for now.

**Comment by sg-** [comment]
There is an at parser in Mbed OS but I wouldn't suggest moving to it as of yet. It didn't land in a backwards compatible way to there is some ongoing work to resolve this. @SenRamakri

**Comment by betzw** [comment]
@janjongboom, is having to choose between different versions of the same lib/repo really an additional issue? I mean as of today, in case of different versions of the same lib/repo the build will simply fail due to either compilation or link problems (as discussed [above](https://github.com/ARMmbed/easy-connect/pull/42#issuecomment-328818281)). The same (or a similar error) could still happen (or explicitly be raised) even if we are checking for a lib/repo being reference more than one time.

**Comment by betzw** [comment]
I have just updated this PR to reflect the [proposal](https://github.com/ARMmbed/easy-connect/pull/42#issuecomment-328845460) of @JammuKekkonen. 
@JanneKiiskila, pls. let me know how you intend to proceed.

cc @screamerbg

**Comment by screamerbg** [comment]
Thanks @betzw. @JanneKiiskila @JammuKekkonen are you happy with the PR?

**Comment by betzw** [comment]
Sorry for this, but there yesterday there was an important bug fix in `ATParser` for which I am just waiting that the [PR](https://github.com/ARMmbed/ATParser/pull/16) gets merged in.
So could you pls. wait a bit before merging this PR until I can update the `ATParser.lib` file with the new sha-id. 
**I will keep you informed!**

**Comment by JanneKiiskila** [comment]
No problem @betzw , just let us know when you're OK.
We should perhaps add an "do not merge yet" flag.

**Comment by betzw** [comment]
@JanneKiiskila, OK ready for merging again!

**Pull request merged**
