### PR TITLE
Update wifi-ism43362

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Quite a lot of changes.

117eb2d (HEAD, origin/master, origin/HEAD) Fix commit merge issue
f6cd428 Merge remote-tracking branch 'jerome/PR_EXTENDED_TEST'
7c649ec Merge remote-tracking branch 'jerome/PR_VERSION'
4131722 Merge remote-tracking branch 'jerome/PR_DEBUG'
42988fe Merge remote-tracking branch 'jerome/PR_TIMEOUT'
cb8eaef Don't remove 0x0A0D in the DATA part
6b631d0 Use ES_WIFI_MAX_TX_PACKET_SIZE in send procedure
3a099eb Rework timeout code
7d8b4a4 Update debug console print
03bdf29 Create LATEST_FW_VERSION_NUMBER define
750fc65 Update firmware version read
d939f07 Merge pull request #23 from AnttiKauppila/master
5cb314a Default value used from mbed_lib.json
36d4e78 Socket open should be rejected when server is not defined
f01cb2c Merge pull request #19 from jeromecoutant/PR_ASTYLE
97df043 ASTYLE updates
0b635e8 Merge pull request #9 from jeromecoutant/PR_SCAN_TEST
929f839 Check ISM43362 chip connection and version during init
780f6e9 Scan with null pointer.
d0458b1 Increasse SPI buffer size for scan

### CODE REVIEW

**Comment by marcuschangarm** [comment]
Do we know what version of Mbed OS this should work on? I'm getting out-of-memory faults when I try to test it on DISCO_L475VG_IOT01A.

**Comment by marcuschangarm** [comment]
Looks like we need this PR first: https://github.com/ARMmbed/mbed-os/pull/7390

**Comment by JanneKiiskila** [comment]
Good spotting @marcuschangarm , I wonder where this dependency should be documented!
Would it work with an older Mbed OS 5.8 release, as this change seems to be a mistake, i.e. it used to be there?

**Comment by marcuschangarm** [comment]
I just received some ism43362 arduino shields. If this driver works with the shields we don't have a dependency on DISCO_L475VG_IOT01A and we can merge this as is.

**Review by marcuschangarm — APPROVED** [review]
With the memory fix on Mbed OS master I've been able to test the new version.

**Pull request merged**
