### PR TITLE
adding wnc-driver to easy-connect

### PR DESCRIPTION
**Pull request by ghost**
This pull request is a replacement for the previous pull request (#72) to clean out the history associated with it.  The WNC driver itself has been moved to a separate repository hosted by Avnet. 

This pull request is to add a Network Interface for the WNC M14A2A Cellular Data Module that is used on the AT&T IoT Starter Kit (http://cloudconnectkits.org/product/att-iot-starter-kit-powered-aws). The code has been tested using the mbed greentea netsocket tests as well as mbed-stress-test (https://github.com/ARMmbed/mbed-stress-test).

This interface uses  the BufferedSerial library becuase the M14A2A communicates via the UART .  This information was documented in the README.md .

### CODE REVIEW

**Comment by teetak01** [comment]
Check the compilation issue:

```
Compile [  7.0%]: WNC14A2AInterface.cpp
[Fatal Error] WNCDebug.h@35,28: BufferedSerial.h: No such file or directory
[ERROR] In file included from ./easy-connect/wnc14a2a-driver/WNC14A2AInterface/WNC14A2AInterface.h:39:0,
                 from ./easy-connect/wnc14a2a-driver/WNC14A2AInterface/WNC14A2AInterface.cpp:31:
./easy-connect/wnc14a2a-driver/WNC14A2AInterface/WNCDebug.h:35:28: fatal error: BufferedSerial.h: No such file or directory
 #include "BufferedSerial.h"

```

**Comment by ghost** [comment]
@teetak01 this error is because the BufferedSerial library (http://os.mbed.com/users/sam_grove/code/BufferedSerial/). has not been added.  Should I include a lib file in the wnc driver directory to include this library automatically?

**Review by teetak01 — CHANGES_REQUESTED** [review]
This should compile with GCC6, ARMC5, ARMC6 + IAR7.

```
[Warning] BufferedSerial.cpp@29,0:  #1361-D: function "mbed::SerialBase::attach(T *, void (T::*)(), mbed::SerialBase::IrqType) [with T=BufferedSerial]" (declared at line 117 of "./mbed-os/drivers/SerialBase.h") was declared "deprecated"
[Error] BufferedSerial.cpp@84,0:  #28: expression must have a constant value
[Error] BufferedSerial.cpp@84,0:  #60: this operator is not allowed in an integral constant expression
```

**Comment by ghost** [comment]
wnc14a2a-driver updated, removed BufferedSerial library and switched to UARTSerial instead. New library is 41b74c1d9fb52cb229e26f18c2d81caf21d7da78

**Comment by MarceloSalazar** [comment]
@dlfryar I understand you've been working on this. can you please review?

**Comment by dlfryar-zz** [comment]
Pulling in these changes to test, but it looks like it still needs a squash on the last four commits.

Squash commits example

git reset --soft HEAD~4 && git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"

**Pull request closed without merging**
