### PR TITLE
README - typical issues

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Some examples of typical issues you might see.
Link to mbed-os-example-client for some examples.

### CODE REVIEW

**Review by peknis01 — APPROVED** [review]
I did some edits and the doc should be fine now. There may be some json syntax issues, as there is something highlighted with red in the code snippets. Please check them.

**Comment by JanneKiiskila** [comment]
@peknis01 , fixed the JSON }-issue and squashed your edits into one commit.

**Comment by janjongboom** [comment]
@JanneKiiskila The Nanostack errors should be fixed higher up, we can't bother the user with this, especially when they do not even know they use easy-connect.

**Comment by JanneKiiskila** [comment]
@janjongboom - what do you mean? "he Nanostack errors should be fixed higher up"? Change documentation or fix some mbed build tools?-)

**Comment by janjongboom** [comment]
@JanneKiiskila Well, if I'm not using nanostack and it throws a build error the solution should not be to create an `mbedignore` file, but rather fix the build error...

**Pull request merged**
