### PR TITLE
CI-test

### PR DESCRIPTION
**Pull request by teetak01**

### CODE REVIEW

**Review by janjongboom — CHANGES_REQUESTED** [review]
???

**Comment by teetak01** [comment]
:-) This is PR test for new CI-automation I started to do for this repository. Just missing some access-rights for the CI-bots.

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
CI-build jobs automated and made mandatory.

**Pull request closed without merging**
