### PR TITLE
Enable REALTEK_RTL8195AM WiFi

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Changes needed for the addition of the RTL Wifi-stack to enable REALTEK_RTL8195AM.
README.md also updated.

### CODE REVIEW

**Review by bulislaw — APPROVED** [review]
LGTM

**Comment by JanneKiiskila** [comment]
Test on-going here, https://github.com/ARMmbed/mbed-os-example-client/pull/267
- that is a regression set.

I can't get the RTL WIFI to REALLY work, but it's not an issue in THIS code, IMHO.

**Comment by bulislaw** [comment]
The wifi example works fine, it doesn't do much, but the connection is established and http transaction is successful : https://github.com/ARMmbed/mbed-os-example-wifi

**Comment by JanneKiiskila** [comment]
Ok, WiFi now seems to work, there was some temporary (?) problem with our RaaS WiFi (even K64F didn't work for a while).  Now it worked, but the actual client connection still failed. Now the Ameba device in CI also got stuck completely, but those are different issues in that sense.

**Comment by JanneKiiskila** [comment]
Hmh... Killed another device as well in RaaS now (mbed_REALTEK_RTL8195AM#5). Nice.

**Comment by janjongboom** [comment]
@JanneKiiskila I was on holiday, but should this not be called `WIFI_RTL8195`. Now we need to rely on Realtek to keep the interface the same for all Realtek drivers...

**Comment by JanneKiiskila** [comment]
I would be sort of wanting to have less interfaces, rather than  more!

**Comment by janjongboom** [comment]
@JanneKiiskila Yeah, but if Realtek makes a `RTL8196` which uses a different driver then we have a problem.

**Comment by JanneKiiskila** [comment]
We can do a new PR and rename the WIFI_REALTEK to WIFI_RTL8195A. But, I would really want the mbed OS developers to try to cut down on the # of stacks. Even if you have different HW, it doesn't mean you must have different stack!

**Pull request merged**
