### PR TITLE
Add support for the ESP32.

### PR DESCRIPTION
**Pull request by d-kato**

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
@d-kato  - could you recommend some add-on board for verifying these changes? 

(There does not seem to be Arduino compatible add-on board for these).

**Comment by JanneKiiskila** [comment]
Does this stack pass the [mbed-stress-test](https://github.com/ARMmbed/mbed-stress-test)?

**Comment by d-kato** [comment]
I could not find a general Arduino shield.
If it is for GR-PEACH, "GR-PEACH Wireless CAMERA Shield" will be prepared.
But, there is no detailed explanation page yet.But, there is no detailed explanation page yet.
In the case of GR-LYCHEE, ESP32 is mounted on the board.

Sorry. I will try mbed-stress-test.

**Comment by d-kato** [comment]
I will cancel PR for the following reasons.

It does not work if you read a large amount of data simultaneously with multiple sockets.
So "tests-stress-network-http-multiple" does not pass.
Other tests passed.
I think it is a problem with ESP32 firmware.

- It does not work even with a single task.
- It does not work even at low baud rate.
- It does not work even if buffer size of UART is increased. (drivers.uart-serial-rxbuf-size)

**Comment by JanneKiiskila** [comment]
There is work on-going (https://github.com/ARMmbed/esp8266-driver/issues/77) even on the ESP8266 firmware to enable the flow control (which is exactly the reason why these failures are happening), I would recommend keeping an eye on that and giving this another go once that gets resolved (I would **assume** they would push the same fix also for the ESP32 as well).

**Comment by d-kato** [comment]
I already tried UART flow control with ESP32. Even if the baud rate is increased, it is possible to transfer a small buffer size, so I think the flow control itself is moving.

https://github.com/d-kato/easy-connect/commit/9e4bc8b26594ae5f73d66de6ec6849d061abeb87
https://github.com/d-kato/esp32-driver/commit/78a139f3bce17e23f2b4bd9342dd7adca023d248

However, "tests-stress-network-http-multiple" does not pass. So I thought it was a different problem.

The link destination information is the flow control of the TCP transfer itself. As you said, similar processing may be required for ESP32.

**Pull request closed without merging**
