### PR TITLE
Align config names, macros, etc. with correct names of STM's Wi-Fi boards

### PR DESCRIPTION
**Pull request by betzw**
@JanneKiiskila,
For which reason did you add definitions for `IDW01M1` and `IDW01A1` (which should be `IDW04A1`) in file [`easy-connect.h`](https://github.com/ARMmbed/easy-connect/blob/master/easy-connect.h#L32-L35)? These are already defined in file [`SpwfSAInterface.h`](https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/blob/master/SpwfSAInterface.h#L43-L44), which should be sufficient!?!
Maybe you did this just because of the wrong name you used, i.e.: IDW0*1*A1 rather than IDW0**4**A1?!?

### CODE REVIEW

**Comment by betzw** [comment]
Pls. **note**, this is an urgent PR as currently compilation for expansion board `X-NUCLEO-IDW04A1` fails when following the documentation of the [X-NUCLEO-IDW0xx1 Wi-Fi Driver](https://github.com/ARMmbed/wifi-x-nucleo-idw01m1)!

**Review by JanneKiiskila — APPROVED** [review]
Looks good to me.

**Comment by JanneKiiskila** [comment]
My bad, apologies for the inconvenience @betzw.

**Comment by betzw** [comment]
Sorry @JanneKiiskila, but I forgot to put another modification in the sources without which this PR will not work for any STM Wi-Fi shield :open_mouth: 
Will come up with an additional PR asap!

**Pull request merged**
