### PR TITLE
Hexiwear ESP8266 & Nucleo F4x1RE pins to mbed_lib.json

### PR DESCRIPTION
**Pull request by JanneKiiskila**
It needs the pin defines now, it does not have the standard D0/D1.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
`mbed-os-example-client` with Hexiwear works with this one now.

**Comment by janjongboom** [comment]
If we're gonna put this in here, we also need similar ones for NUCLEO boards which use D2/D8 instead of D0/D1. Usually I have this in mbed_app.json (see [here](https://os.mbed.com/teams/sandbox/code/http-example/file/903bdf9a49f4/mbed_app.json/) which also already has HEXIWEAR target set). But I don't object to putting this in mbed_lib.json.

Maybe we should actually find this information from [PeripheralPins](https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_HEXIWEAR/PeripheralPins.c#L79), although there's multiple UART defined in there for Hexiwear, might not be clear which one to use.

**Comment by JanneKiiskila** [comment]
@janjongboom  - yep, added those as well.

**Review by teetak01 — APPROVED** [review]

**Comment by JanneKiiskila** [comment]
@janjongboom  - the UART enum - well, I think the end users will find it clearer this way.

**Review by janjongboom — APPROVED** [review]

**Pull request merged**
